### ISSUE TITLE
Cannot extracts city when sentence is too long.

### ISSUE THREAD

**Issue by tanchekwei** [elyase/geotext#14]
### OS name and version
Windows 10, Version 1803

### Any details about your local setup that might be helpful in troubleshooting.
I am doing my ChatBot assignment that can tell user the weather.

So, I using geotext to extract cities from the user input

But I found that when the sentence is too long, it cannot return the city I want.

### Detailed steps to reproduce the bug.

Codes:

```
from geotext import GeoText


def main():
    while True:
        request = input("Enter sentence containing a location: ")
        places = GeoText(request.title())

        print("Cities in the sentence: " + places.cities)


if __name__ == '__main__':
    main()
```

Output:

```
Enter sentence containing a location: what is the weather today in kuala lumpur?
Cities in the sentence: ['Kuala Lumpur']
Enter sentence containing a location: please tell me the weather today in New York
Cities in the sentence: ['York']
Enter sentence containing a location: Washington
Cities in the sentence: ['Washington']

Enter sentence containing a location: can you please tell me the weather today in kuala lumpur?
Cities in the sentence: []
Enter sentence containing a location: can you please tell me the weather today in london?
Cities in the sentence: []
Enter sentence containing a location: please tell me the weather today in Washington
Cities in the sentence: []
Enter sentence containing a location: what is the weather in Washington?
Cities in the sentence: []
```

**Comment by iwpnd** [comment]
The problem is not with geotext in particular but with .title(). Title function in python is the Python String Method which is used to convert the first character in each word to Uppercase and remaining characters to Lowercase in string and returns new string.
Geotext is based on a regex statement that matches named entities that start with a capital letter. What you are doing is turning every word in the sentence to a named entity. This leads to geotext messing up the matching. 
I‘m currently on mobile right now and cannot test, but I’m fairly certain that it would work if you input a proper string with the City named starting with a capital letter only. 
Hope this helps.
